' Gambas module file

Public Function TestCai(Cai As String) As String
  
  Dim Lig As String
  Dim $Vdr As String
  Dim Filetxt As String
  Dim hfile As File
  
  Filetxt = User.home & "/" & "Caisse" & Cai & ".lock"
  If Exist(Filetxt) Then
    ' [GB2:OPEN] OPEN filetxt FOR READ AS #hFile
    hFile = Open filetxt For Read
    Line Input #hFile, Lig
    $Vdr = Lig
    Close #hFile
  Endif
  Return $Vdr
  
End
