' Gambas module file

'****************On enregistre le code postal******************************
Public Sub Ecp(cpostal As String, burdist As String)

  Dim Rpost As Result

  If Cpostal <> "" Then
    Rpost = Utils.db.Exec("SELECT * FROM Fiches_Cpostaux WHERE cp = &1 and burdist = &2", Cpostal, Burdist)
    If Not Rpost.Available Then Utils.db.Exec("INSERT INTO Fiches_Cpostaux (cp,burdist) VALUES (&1, &2)", Cpostal, Burdist)
  Endif

End
