' Gambas module file

Public Sub Verif_Maj()

  Dim version As String
  Dim txt As String
  Dim $hform As Form
  Dim hLabel As Label

  $hForm = New Form As "Form"
  $hForm.Border = Border.Etched
  $hform.Title = "Mise à jour de Laurux"
  hLabel = New Label($hForm)
  hLabel.Text = "La mise à jour prend quelques minutes.\n Veuillez patienter SVP."
  hLabel.Background = &EBEBEB&
  hLabel.Width = 600
  hLabel.Alignment = 3
  hLabel.Height = $hform.Height / 2
  hLabel.Border = Border.Plain
  hLabel.Text = "La mise à jour prend quelques minutes.\n Veuillez patienter SVP."
  $hForm.Move($hForm.ScreenX, $hForm.ScreenY, 600, 200)
  $hform.Center
  Version = Start.LocalSettings["/dbase/Version"]
  If Exist(User.Home & "/version.txt") Then Kill User.Home & "/version.txt"
  Shell "wget -q" & " " & "http://www.laurux.fr/version.txt" & " -O " & User.Home & "/version.txt" Wait
  If Exist(User.Home & "/version.txt") Then
    txt = Trim$(File.Load(User.Home & "/version.txt"))
    If Not IsNull(Val(Right$(version, 4))) And If Not IsNull(txt) Then
      If Val(Right$(txt, 4)) > Val(Right$(version, 4)) Then
        If Message.Question("Attention ! Vous allez mettre à jour votre logiciel Laurux \n Vous devez être connecté au réseau internet. \n Etes-vous d'accord ?", "Oui", "Non") = "1" Then
          $hform.Mouse = Mouse.Wait
          Try Move Application.Path & "/Laurux.gambas" To Application.Path & "/Laurux.old.gambas"
          Shell "cd " & User.Home & ""
          $hForm.Show
          Wait 1
          Shell "wget http://www.laurux.fr/Laurux.tar.gz -O " & User.Home & "/Laurux.tar.gz" Wait
          Shell "cd " & User.Home & " " & "; tar xvfz " & User.Home & "/Laurux.tar.gz" Wait
          Kill User.Home & "/Laurux.tar.gz"
          Kill User.Home & "/version.txt"
          $hform.Close
          $hform.Mouse = Mouse.Default
          Start.LocalSettings["/Affmaj"] = 1
          Start.LocalSettings.Save
          Message.Warning("Mise à jour terminée ! Veuillez relancer Laurux SVP !")
        Endif
      Else
        Message.Warning("Aucune mise à jour n'est a faire !")
      Endif
    Endif
  Else
    $hform.Mouse = Mouse.Default
    Message.Warning("Problème de mise à jour! Veuillez vérifier votre connexion SVP.")
  Endif
  If Exist(User.Home & "/version.txt") Then Kill User.Home & "/version.txt"

End
