' Gambas module file

'Fonction pour récuperer le groupe de l'utilisateur.
Public Function Group() As String
  
  Dim gid As String
  Dim Hfile As File
  Dim Lig As String
  Dim Key As String
  Dim iPos As Integer
  
  gid = User.Group
  Shell "getent group " & gid & " > /tmp/group 2>&1" Wait
  If Exist("/tmp/group") Then
    HFile = Open "/tmp/group" For Read
    Lig = File.Load("/tmp/group")
  Endif
  Line Input #hFile, Lig
  iPos = InStr(Lig, ":")
  Key = Left$(Lig, iPos - 1)
  Return key
  
End

Public Function Utilisateur() As String
  
  Return User.Name
  
End
