' Gambas module file

Public Sub Prog(Fic As String) As String

  Dim $Exec As String

  If Start.LocalSettings["/CmdVis"] Then
    Shell Start.LocalSettings["/CmdVis"] & " " & Fic
  Else
    $Exec = "xdg-open"
    If Not CheckProg.Chk($Exec) Then $Exec = "evince"
    If Not CheckProg.Chk($Exec) Then $Exec = "okular"
    If Not CheckProg.Chk($Exec) Then $Exec = "acroread"
    If Not CheckProg.Chk($Exec) Then $Exec = "kprint"
    If Not CheckProg.Chk($Exec) Then $Exec = "atril"
    Shell $Exec & " " & Fic
  Endif

End
